# Домашнее задание «Библиотека numpy. Вычислительные задачи»

# Задание 1

In [14]:
import numpy as np

N = 15
np.arange(0, N)[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Задание 2

In [15]:
N = 7
M = np.diag(np.arange(0, N)[::-1])
print(M)

[[6 0 0 0 0 0 0]
 [0 5 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 2 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]]


In [16]:
np.trace(M)

21

# Задание 3

In [19]:
from numpy import linalg

'''
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
'''

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

b = np.array( [ 4, 12 , -3 ] )

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

# Задание 4

In [20]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

for user, stats in enumerate(users_stats):
    print(user+1, cosine(stats,next_user_stats))


1 0.19999999999999996
2 0.8451542547285165
3 0.3999999999999999
4 0.7905694150420948
5 0.3999999999999999
6 0.0
7 0.0
8 0.9486832980505138
9 0.0
10 0.0


In [22]:
cosines = [cosine(stats,next_user_stats) for stats in users_stats]
max_cos = max(cosines)
similar_user = cosines.index(max_cos) + 1 

print(f'Cамый похожий пользователь USER ID = {similar_user}, косинусное сходство {round(max_cos,4)}')

Cамый похожий пользователь USER ID = 8, косинусное сходство 0.9487
